name: vin_decoder
description:
  Dart library for working with Vehicle Identification Numbers (VINs) based on ISO 3779:2009 and
  World Manufacturer Identifiers (WMIs) based on ISO 3780:2009, enriched by NHTSA data.

version: 0.1.2
repository: https://github.com/adaptant-labs/vin-decoder-dart
issue_tracker: https://github.com/adaptant-labs/vin-decoder-dart/issues

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.3.0
  basic_utils: ^2.7.0
  http: ^0.12.2
  random_string: ^2.1.0

dev_dependencies:
  test: ^1.16.2
